import derived

def main():
    tree = derived.Derived_BST()        
    tree.insert(12)
    tree.insert(5)
    tree.insert(46)
    tree.insert(80)
    tree.insert(30)
    tree.insert(2)
    tree.insert(56)
    tree.insert(25)
    tree.insert(10)
    max = tree.get_max()
    min = tree.get_min()
    print(f"Max value: {max}")
    print(f"Min value: {min}")
    value = 37
    tree.insert(value)
    node = tree.find_node(value)
    print(f"New node 37 has been added to the tree")
    print(f"37 is a leaf node?: {tree.is_leaf(node)}")
    print(f"37 is a branch node?: {tree.is_branch(node)}")
    print(f"{tree.parent_node(value)} is the parent node of {value}")
    print(f"total leaf nodes: {tree.total_leaf_nodes(tree.root)}")
    print(f"total non leaf nodes: {tree.total_nonleaf_nodes()}")
    print("Breadth-First Traversal:")
    tree.breadth_first()
main()